[package]
name = "game"
version = "0.1.0"
authors = ["Benedict Aas <x+g@shou.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
three = "0.4.0"
mint = "*"
glutin = "*"
